services:
  postgres:
    image: postgres:16
    container_name: postgres-imc
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - microservices

  imc-backend:
    image: node:20
    container_name: imc-service
    working_dir: /app
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "npm install && npm run start:dev"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_SSL: false
      PORT: ${PORT}
      AUTH_API_URL: http://auth-service:3001
    networks:
      - microservices

volumes:
  postgres_data:

networks:
  microservices:
    name: shared-microservices
    external: false
