services:
  mongodb:
    image: mongo:7
    container_name: mongodb-imc
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: imc_db
    networks:
      - microservices

  imc-backend:
    image: node:20
    container_name: imc-service
    working_dir: /app
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "npm install && npm run start:dev"
    environment:
      MONGO_URI: mongodb://mongodb:27017/imc_db
      MONGO_HOST: mongodb
      MONGO_PORT: 27017
      MONGO_DATABASE: imc_db
      PORT: ${PORT}
      AUTH_API_URL: http://auth-service:3001
    networks:
      - microservices

volumes:
  mongo_data:

networks:
  microservices:
    name: shared-microservices
    external: false
